repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest commit SHA / tag
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: https://github.com/psf/black
    rev: 23.11.0  # Use the latest commit SHA / tag
    hooks:
    -   id: black
        language_version: python3.11  # Ensure you use the correct Python version
-   repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.83.3  # Replace with the latest version
    hooks:
    -   id: cfn-python-lint
        files: template.yaml

# Add more hooks/repositories here
